# site
title: Sumeet Bansal
description: Student and Full-Stack Software Developer.
url: https://sumeet-bansal.github.io
logo: profile.png
locale: en_US

# left block images
background:
  homepage: images/home.png
  post-list: images/bold-and-brash.jpg
  default-post: images/bold-and-brash.jpg

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-116299114-1

# social links
email:             sumeetbansal@gmail.com
#google.plus:       username
twitter:           shmetbansal
#facebook:          username
github:            sumeet-bansal
#stackoverflow:     8544720/sbansal
linkedin:          s-bansal
#instagram:         whyissumeetbansaltaken
#lastfm:            sbansal21
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             mrgoodbytes21
#dribbble:          username
#youtube:           username
#soundcloud:        sumeet-bansal-1
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
phone:             1 (408) 250-3097

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
